// Package saviyntecf provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package saviyntecf

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Accounts defines model for accounts.
type Accounts struct {
	Accounts *[]struct {
		ACCOUNTCLASS             *string `json:"ACCOUNTCLASS,omitempty"`
		ACCOUNTID                *string `json:"ACCOUNTID,omitempty"`
		ACCOUNTTYPE              *string `json:"ACCOUNTTYPE,omitempty"`
		COMMENTS                 *string `json:"COMMENTS,omitempty"`
		CUSTOMPROPERTY1          *string `json:"CUSTOMPROPERTY1,omitempty"`
		CUSTOMPROPERTY10         *string `json:"CUSTOMPROPERTY10,omitempty"`
		CUSTOMPROPERTY11         *string `json:"CUSTOMPROPERTY11,omitempty"`
		CUSTOMPROPERTY12         *string `json:"CUSTOMPROPERTY12,omitempty"`
		CUSTOMPROPERTY13         *string `json:"CUSTOMPROPERTY13,omitempty"`
		CUSTOMPROPERTY14         *string `json:"CUSTOMPROPERTY14,omitempty"`
		CUSTOMPROPERTY15         *string `json:"CUSTOMPROPERTY15,omitempty"`
		CUSTOMPROPERTY16         *string `json:"CUSTOMPROPERTY16,omitempty"`
		CUSTOMPROPERTY17         *string `json:"CUSTOMPROPERTY17,omitempty"`
		CUSTOMPROPERTY18         *string `json:"CUSTOMPROPERTY18,omitempty"`
		CUSTOMPROPERTY19         *string `json:"CUSTOMPROPERTY19,omitempty"`
		CUSTOMPROPERTY2          *string `json:"CUSTOMPROPERTY2,omitempty"`
		CUSTOMPROPERTY20         *string `json:"CUSTOMPROPERTY20,omitempty"`
		CUSTOMPROPERTY21         *string `json:"CUSTOMPROPERTY21,omitempty"`
		CUSTOMPROPERTY22         *string `json:"CUSTOMPROPERTY22,omitempty"`
		CUSTOMPROPERTY23         *string `json:"CUSTOMPROPERTY23,omitempty"`
		CUSTOMPROPERTY24         *string `json:"CUSTOMPROPERTY24,omitempty"`
		CUSTOMPROPERTY25         *string `json:"CUSTOMPROPERTY25,omitempty"`
		CUSTOMPROPERTY26         *string `json:"CUSTOMPROPERTY26,omitempty"`
		CUSTOMPROPERTY27         *string `json:"CUSTOMPROPERTY27,omitempty"`
		CUSTOMPROPERTY28         *string `json:"CUSTOMPROPERTY28,omitempty"`
		CUSTOMPROPERTY29         *string `json:"CUSTOMPROPERTY29,omitempty"`
		CUSTOMPROPERTY3          *string `json:"CUSTOMPROPERTY3,omitempty"`
		CUSTOMPROPERTY30         *int    `json:"CUSTOMPROPERTY30,omitempty"`
		CUSTOMPROPERTY31         *string `json:"CUSTOMPROPERTY31,omitempty"`
		CUSTOMPROPERTY32         *string `json:"CUSTOMPROPERTY32,omitempty"`
		CUSTOMPROPERTY33         *string `json:"CUSTOMPROPERTY33,omitempty"`
		CUSTOMPROPERTY34         *string `json:"CUSTOMPROPERTY34,omitempty"`
		CUSTOMPROPERTY35         *string `json:"CUSTOMPROPERTY35,omitempty"`
		CUSTOMPROPERTY36         *string `json:"CUSTOMPROPERTY36,omitempty"`
		CUSTOMPROPERTY37         *string `json:"CUSTOMPROPERTY37,omitempty"`
		CUSTOMPROPERTY38         *string `json:"CUSTOMPROPERTY38,omitempty"`
		CUSTOMPROPERTY39         *string `json:"CUSTOMPROPERTY39,omitempty"`
		CUSTOMPROPERTY4          *string `json:"CUSTOMPROPERTY4,omitempty"`
		CUSTOMPROPERTY40         *string `json:"CUSTOMPROPERTY40,omitempty"`
		CUSTOMPROPERTY41         *string `json:"CUSTOMPROPERTY41,omitempty"`
		CUSTOMPROPERTY42         *string `json:"CUSTOMPROPERTY42,omitempty"`
		CUSTOMPROPERTY43         *string `json:"CUSTOMPROPERTY43,omitempty"`
		CUSTOMPROPERTY44         *string `json:"CUSTOMPROPERTY44,omitempty"`
		CUSTOMPROPERTY45         *string `json:"CUSTOMPROPERTY45,omitempty"`
		CUSTOMPROPERTY46         *string `json:"CUSTOMPROPERTY46,omitempty"`
		CUSTOMPROPERTY47         *string `json:"CUSTOMPROPERTY47,omitempty"`
		CUSTOMPROPERTY48         *string `json:"CUSTOMPROPERTY48,omitempty"`
		CUSTOMPROPERTY49         *string `json:"CUSTOMPROPERTY49,omitempty"`
		CUSTOMPROPERTY5          *string `json:"CUSTOMPROPERTY5,omitempty"`
		CUSTOMPROPERTY50         *string `json:"CUSTOMPROPERTY50,omitempty"`
		CUSTOMPROPERTY51         *string `json:"CUSTOMPROPERTY51,omitempty"`
		CUSTOMPROPERTY52         *string `json:"CUSTOMPROPERTY52,omitempty"`
		CUSTOMPROPERTY53         *string `json:"CUSTOMPROPERTY53,omitempty"`
		CUSTOMPROPERTY54         *string `json:"CUSTOMPROPERTY54,omitempty"`
		CUSTOMPROPERTY55         *string `json:"CUSTOMPROPERTY55,omitempty"`
		CUSTOMPROPERTY56         *string `json:"CUSTOMPROPERTY56,omitempty"`
		CUSTOMPROPERTY57         *string `json:"CUSTOMPROPERTY57,omitempty"`
		CUSTOMPROPERTY58         *string `json:"CUSTOMPROPERTY58,omitempty"`
		CUSTOMPROPERTY59         *string `json:"CUSTOMPROPERTY59,omitempty"`
		CUSTOMPROPERTY6          *string `json:"CUSTOMPROPERTY6,omitempty"`
		CUSTOMPROPERTY60         *string `json:"CUSTOMPROPERTY60,omitempty"`
		CUSTOMPROPERTY7          *string `json:"CUSTOMPROPERTY7,omitempty"`
		CUSTOMPROPERTY8          *string `json:"CUSTOMPROPERTY8,omitempty"`
		CUSTOMPROPERTY9          *string `json:"CUSTOMPROPERTY9,omitempty"`
		DESCRIPTION              *string `json:"DESCRIPTION,omitempty"`
		DISPLAYNAME              *string `json:"DISPLAYNAME,omitempty"`
		INCORRECTLOGONS          *string `json:"INCORRECTLOGONS,omitempty"`
		LASTLOGONDATE            *string `json:"LASTLOGONDATE,omitempty"`
		LASTPASSWORDCHANGE       *string `json:"LASTPASSWORDCHANGE,omitempty"`
		LOCKEDSTATE              *string `json:"LOCKEDSTATE,omitempty"`
		NAME                     *string `json:"NAME,omitempty"`
		PASSWORDCHANGESTATUS     *string `json:"PASSWORDCHANGESTATUS,omitempty"`
		PASSWORDLOCKDATE         *string `json:"PASSWORDLOCKDATE,omitempty"`
		STATUS                   *int    `json:"STATUS,omitempty"`
		TARGETLASTPASSWORDCHANGE *string `json:"TARGETLASTPASSWORDCHANGE,omitempty"`
		UPDATEDATE               *string `json:"UPDATEDATE,omitempty"`
		VALIDFROM                *string `json:"VALIDFROM,omitempty"`
		VALIDTHROUGH             *string `json:"VALIDTHROUGH,omitempty"`
	} `json:"accounts,omitempty"`
	Offset     *string `json:"offset,omitempty"`
	Pagesize   *int    `json:"pagesize,omitempty"`
	TotalCount *int    `json:"totalCount,omitempty"`
}

// Createaccount defines model for createaccount.
type Createaccount struct {
	AccountID         *string `json:"accountID,omitempty"`
	Customproperty1   *string `json:"customproperty1,omitempty"`
	Email             *string `json:"email,omitempty"`
	EmployeeType      *string `json:"employeeType,omitempty"`
	Firstname         *string `json:"firstname,omitempty"`
	Jobcodedesc       *string `json:"jobcodedesc,omitempty"`
	Lastname          *string `json:"lastname,omitempty"`
	Manager           *string `json:"manager,omitempty"`
	Middlename        *string `json:"middlename,omitempty"`
	PreferedFirstName *string `json:"preferedFirstName,omitempty"`
	Statuskey         *string `json:"statuskey,omitempty"`
}

// Groups defines model for groups.
type Groups struct {
	Groups *[]struct {
		CUSTOMPROPERTY1   *string    `json:"CUSTOMPROPERTY1,omitempty"`
		CUSTOMPROPERTY10  *string    `json:"CUSTOMPROPERTY10,omitempty"`
		CUSTOMPROPERTY11  *string    `json:"CUSTOMPROPERTY11,omitempty"`
		CUSTOMPROPERTY12  *string    `json:"CUSTOMPROPERTY12,omitempty"`
		CUSTOMPROPERTY13  *string    `json:"CUSTOMPROPERTY13,omitempty"`
		CUSTOMPROPERTY14  *string    `json:"CUSTOMPROPERTY14,omitempty"`
		CUSTOMPROPERTY15  *string    `json:"CUSTOMPROPERTY15,omitempty"`
		CUSTOMPROPERTY16  *string    `json:"CUSTOMPROPERTY16,omitempty"`
		CUSTOMPROPERTY17  *string    `json:"CUSTOMPROPERTY17,omitempty"`
		CUSTOMPROPERTY18  *string    `json:"CUSTOMPROPERTY18,omitempty"`
		CUSTOMPROPERTY19  *string    `json:"CUSTOMPROPERTY19,omitempty"`
		CUSTOMPROPERTY2   *time.Time `json:"CUSTOMPROPERTY2,omitempty"`
		CUSTOMPROPERTY20  *string    `json:"CUSTOMPROPERTY20,omitempty"`
		CUSTOMPROPERTY21  *string    `json:"CUSTOMPROPERTY21,omitempty"`
		CUSTOMPROPERTY22  *string    `json:"CUSTOMPROPERTY22,omitempty"`
		CUSTOMPROPERTY23  *string    `json:"CUSTOMPROPERTY23,omitempty"`
		CUSTOMPROPERTY24  *string    `json:"CUSTOMPROPERTY24,omitempty"`
		CUSTOMPROPERTY25  *string    `json:"CUSTOMPROPERTY25,omitempty"`
		CUSTOMPROPERTY26  *string    `json:"CUSTOMPROPERTY26,omitempty"`
		CUSTOMPROPERTY27  *string    `json:"CUSTOMPROPERTY27,omitempty"`
		CUSTOMPROPERTY28  *string    `json:"CUSTOMPROPERTY28,omitempty"`
		CUSTOMPROPERTY29  *string    `json:"CUSTOMPROPERTY29,omitempty"`
		CUSTOMPROPERTY3   *time.Time `json:"CUSTOMPROPERTY3,omitempty"`
		CUSTOMPROPERTY30  *int       `json:"CUSTOMPROPERTY30,omitempty"`
		CUSTOMPROPERTY31  *string    `json:"CUSTOMPROPERTY31,omitempty"`
		CUSTOMPROPERTY32  *string    `json:"CUSTOMPROPERTY32,omitempty"`
		CUSTOMPROPERTY33  *string    `json:"CUSTOMPROPERTY33,omitempty"`
		CUSTOMPROPERTY34  *string    `json:"CUSTOMPROPERTY34,omitempty"`
		CUSTOMPROPERTY35  *string    `json:"CUSTOMPROPERTY35,omitempty"`
		CUSTOMPROPERTY36  *string    `json:"CUSTOMPROPERTY36,omitempty"`
		CUSTOMPROPERTY37  *string    `json:"CUSTOMPROPERTY37,omitempty"`
		CUSTOMPROPERTY38  *string    `json:"CUSTOMPROPERTY38,omitempty"`
		CUSTOMPROPERTY39  *string    `json:"CUSTOMPROPERTY39,omitempty"`
		CUSTOMPROPERTY4   *string    `json:"CUSTOMPROPERTY4,omitempty"`
		CUSTOMPROPERTY40  *string    `json:"CUSTOMPROPERTY40,omitempty"`
		CUSTOMPROPERTY5   *string    `json:"CUSTOMPROPERTY5,omitempty"`
		CUSTOMPROPERTY6   *string    `json:"CUSTOMPROPERTY6,omitempty"`
		CUSTOMPROPERTY7   *string    `json:"CUSTOMPROPERTY7,omitempty"`
		CUSTOMPROPERTY8   *string    `json:"CUSTOMPROPERTY8,omitempty"`
		CUSTOMPROPERTY9   *string    `json:"CUSTOMPROPERTY9,omitempty"`
		ChildEntitlements *struct {
			Groups *[]struct {
				EntitlementID *int `json:"entitlementID,omitempty"`
			} `json:"groups,omitempty"`
		} `json:"childEntitlements,omitempty"`
		Description         *string   `json:"description,omitempty"`
		Displayname         *string   `json:"displayname,omitempty"`
		Entclass            *string   `json:"entclass,omitempty"`
		EntitlementID       *int      `json:"entitlementID,omitempty"`
		EntitlementGlossary *string   `json:"entitlement_glossary,omitempty"`
		EntitlementValue    *string   `json:"entitlement_value,omitempty"`
		Owners              *[]string `json:"owners,omitempty"`
		Status              *string   `json:"status,omitempty"`
	} `json:"groups,omitempty"`
	Offset     *string `json:"offset,omitempty"`
	Pagesize   *int    `json:"pagesize,omitempty"`
	TotalCount *int    `json:"totalCount,omitempty"`
}

// Groupsmembership defines model for groupsmembership.
type Groupsmembership struct {
	GroupMemberships *[]struct {
		AccountID     *int `json:"accountID,omitempty"`
		EntitlementID *int `json:"entitlementID,omitempty"`
	} `json:"group_memberships,omitempty"`
}

// Roles defines model for roles.
type Roles struct {
	Offset   *string `json:"offset,omitempty"`
	Pagesize *int    `json:"pagesize,omitempty"`
	Roles    *[]struct {
		CUSTOMPROPERTY1   *string    `json:"CUSTOMPROPERTY1,omitempty"`
		CUSTOMPROPERTY10  *string    `json:"CUSTOMPROPERTY10,omitempty"`
		CUSTOMPROPERTY11  *string    `json:"CUSTOMPROPERTY11,omitempty"`
		CUSTOMPROPERTY12  *string    `json:"CUSTOMPROPERTY12,omitempty"`
		CUSTOMPROPERTY13  *string    `json:"CUSTOMPROPERTY13,omitempty"`
		CUSTOMPROPERTY14  *string    `json:"CUSTOMPROPERTY14,omitempty"`
		CUSTOMPROPERTY15  *string    `json:"CUSTOMPROPERTY15,omitempty"`
		CUSTOMPROPERTY16  *string    `json:"CUSTOMPROPERTY16,omitempty"`
		CUSTOMPROPERTY17  *string    `json:"CUSTOMPROPERTY17,omitempty"`
		CUSTOMPROPERTY18  *string    `json:"CUSTOMPROPERTY18,omitempty"`
		CUSTOMPROPERTY19  *string    `json:"CUSTOMPROPERTY19,omitempty"`
		CUSTOMPROPERTY2   *time.Time `json:"CUSTOMPROPERTY2,omitempty"`
		CUSTOMPROPERTY20  *string    `json:"CUSTOMPROPERTY20,omitempty"`
		CUSTOMPROPERTY21  *string    `json:"CUSTOMPROPERTY21,omitempty"`
		CUSTOMPROPERTY22  *string    `json:"CUSTOMPROPERTY22,omitempty"`
		CUSTOMPROPERTY23  *string    `json:"CUSTOMPROPERTY23,omitempty"`
		CUSTOMPROPERTY24  *string    `json:"CUSTOMPROPERTY24,omitempty"`
		CUSTOMPROPERTY25  *string    `json:"CUSTOMPROPERTY25,omitempty"`
		CUSTOMPROPERTY26  *string    `json:"CUSTOMPROPERTY26,omitempty"`
		CUSTOMPROPERTY27  *string    `json:"CUSTOMPROPERTY27,omitempty"`
		CUSTOMPROPERTY28  *string    `json:"CUSTOMPROPERTY28,omitempty"`
		CUSTOMPROPERTY29  *string    `json:"CUSTOMPROPERTY29,omitempty"`
		CUSTOMPROPERTY3   *time.Time `json:"CUSTOMPROPERTY3,omitempty"`
		CUSTOMPROPERTY30  *int       `json:"CUSTOMPROPERTY30,omitempty"`
		CUSTOMPROPERTY31  *string    `json:"CUSTOMPROPERTY31,omitempty"`
		CUSTOMPROPERTY32  *string    `json:"CUSTOMPROPERTY32,omitempty"`
		CUSTOMPROPERTY33  *string    `json:"CUSTOMPROPERTY33,omitempty"`
		CUSTOMPROPERTY34  *string    `json:"CUSTOMPROPERTY34,omitempty"`
		CUSTOMPROPERTY35  *string    `json:"CUSTOMPROPERTY35,omitempty"`
		CUSTOMPROPERTY36  *string    `json:"CUSTOMPROPERTY36,omitempty"`
		CUSTOMPROPERTY37  *string    `json:"CUSTOMPROPERTY37,omitempty"`
		CUSTOMPROPERTY38  *string    `json:"CUSTOMPROPERTY38,omitempty"`
		CUSTOMPROPERTY39  *string    `json:"CUSTOMPROPERTY39,omitempty"`
		CUSTOMPROPERTY4   *string    `json:"CUSTOMPROPERTY4,omitempty"`
		CUSTOMPROPERTY40  *string    `json:"CUSTOMPROPERTY40,omitempty"`
		CUSTOMPROPERTY5   *string    `json:"CUSTOMPROPERTY5,omitempty"`
		CUSTOMPROPERTY6   *string    `json:"CUSTOMPROPERTY6,omitempty"`
		CUSTOMPROPERTY7   *string    `json:"CUSTOMPROPERTY7,omitempty"`
		CUSTOMPROPERTY8   *string    `json:"CUSTOMPROPERTY8,omitempty"`
		CUSTOMPROPERTY9   *string    `json:"CUSTOMPROPERTY9,omitempty"`
		ChildEntitlements *struct {
			Roles *[]struct {
				EntitlementID *int `json:"entitlementID,omitempty"`
			} `json:"roles,omitempty"`
		} `json:"childEntitlements,omitempty"`
		Description         *string   `json:"description,omitempty"`
		Displayname         *string   `json:"displayname,omitempty"`
		Entclass            *string   `json:"entclass,omitempty"`
		EntitlementID       *int      `json:"entitlementID,omitempty"`
		EntitlementGlossary *string   `json:"entitlement_glossary,omitempty"`
		EntitlementValue    *string   `json:"entitlement_value,omitempty"`
		Owners              *[]string `json:"owners,omitempty"`
		Status              *string   `json:"status,omitempty"`
	} `json:"roles,omitempty"`
	TotalCount *int `json:"totalCount,omitempty"`
}

// Rolesmembership defines model for rolesmembership.
type Rolesmembership struct {
	RoleMemberships *[]struct {
		AccountID     *int `json:"accountID,omitempty"`
		EntitlementID *int `json:"entitlementID,omitempty"`
	} `json:"role_memberships,omitempty"`
}

// Updateuser defines model for updateuser.
type Updateuser struct {
	Customproperty1   *string `json:"customproperty1,omitempty"`
	Email             *string `json:"email,omitempty"`
	EmployeeType      *string `json:"employeeType,omitempty"`
	Firstname         *string `json:"firstname,omitempty"`
	Jobcodedesc       *string `json:"jobcodedesc,omitempty"`
	Lastname          *string `json:"lastname,omitempty"`
	Manager           *string `json:"manager,omitempty"`
	Middlename        *string `json:"middlename,omitempty"`
	PreferedFirstName *string `json:"preferedFirstName,omitempty"`
	Statuskey         *string `json:"statuskey,omitempty"`
}

// Users defines model for users.
type Users struct {
	Offset     *string `json:"offset,omitempty"`
	Pagesize   *int    `json:"pagesize,omitempty"`
	TotalCount *int    `json:"totalCount,omitempty"`
	Users      *[]struct {
		ACCOUNTEXPIRED    *int    `json:"ACCOUNTEXPIRED,omitempty"`
		ACCOUNTLOCKED     *int    `json:"ACCOUNTLOCKED,omitempty"`
		CITY              *string `json:"CITY,omitempty"`
		COMMENTS          *string `json:"COMMENTS,omitempty"`
		COMPANYNAME       *string `json:"COMPANYNAME,omitempty"`
		COSTCENTER        *string `json:"COSTCENTER,omitempty"`
		COUNTRY           *string `json:"COUNTRY,omitempty"`
		CUSTOMPROPERTY1   *string `json:"CUSTOMPROPERTY1,omitempty"`
		CUSTOMPROPERTY10  *string `json:"CUSTOMPROPERTY10,omitempty"`
		CUSTOMPROPERTY11  *string `json:"CUSTOMPROPERTY11,omitempty"`
		CUSTOMPROPERTY12  *string `json:"CUSTOMPROPERTY12,omitempty"`
		CUSTOMPROPERTY13  *string `json:"CUSTOMPROPERTY13,omitempty"`
		CUSTOMPROPERTY14  *string `json:"CUSTOMPROPERTY14,omitempty"`
		CUSTOMPROPERTY15  *string `json:"CUSTOMPROPERTY15,omitempty"`
		CUSTOMPROPERTY16  *string `json:"CUSTOMPROPERTY16,omitempty"`
		CUSTOMPROPERTY17  *string `json:"CUSTOMPROPERTY17,omitempty"`
		CUSTOMPROPERTY18  *string `json:"CUSTOMPROPERTY18,omitempty"`
		CUSTOMPROPERTY19  *string `json:"CUSTOMPROPERTY19,omitempty"`
		CUSTOMPROPERTY2   *string `json:"CUSTOMPROPERTY2,omitempty"`
		CUSTOMPROPERTY20  *string `json:"CUSTOMPROPERTY20,omitempty"`
		CUSTOMPROPERTY21  *string `json:"CUSTOMPROPERTY21,omitempty"`
		CUSTOMPROPERTY22  *string `json:"CUSTOMPROPERTY22,omitempty"`
		CUSTOMPROPERTY23  *string `json:"CUSTOMPROPERTY23,omitempty"`
		CUSTOMPROPERTY24  *string `json:"CUSTOMPROPERTY24,omitempty"`
		CUSTOMPROPERTY25  *string `json:"CUSTOMPROPERTY25,omitempty"`
		CUSTOMPROPERTY26  *string `json:"CUSTOMPROPERTY26,omitempty"`
		CUSTOMPROPERTY27  *string `json:"CUSTOMPROPERTY27,omitempty"`
		CUSTOMPROPERTY28  *string `json:"CUSTOMPROPERTY28,omitempty"`
		CUSTOMPROPERTY29  *string `json:"CUSTOMPROPERTY29,omitempty"`
		CUSTOMPROPERTY3   *string `json:"CUSTOMPROPERTY3,omitempty"`
		CUSTOMPROPERTY30  *string `json:"CUSTOMPROPERTY30,omitempty"`
		CUSTOMPROPERTY31  *string `json:"CUSTOMPROPERTY31,omitempty"`
		CUSTOMPROPERTY32  *string `json:"CUSTOMPROPERTY32,omitempty"`
		CUSTOMPROPERTY33  *string `json:"CUSTOMPROPERTY33,omitempty"`
		CUSTOMPROPERTY34  *string `json:"CUSTOMPROPERTY34,omitempty"`
		CUSTOMPROPERTY35  *string `json:"CUSTOMPROPERTY35,omitempty"`
		CUSTOMPROPERTY36  *string `json:"CUSTOMPROPERTY36,omitempty"`
		CUSTOMPROPERTY37  *string `json:"CUSTOMPROPERTY37,omitempty"`
		CUSTOMPROPERTY38  *string `json:"CUSTOMPROPERTY38,omitempty"`
		CUSTOMPROPERTY39  *string `json:"CUSTOMPROPERTY39,omitempty"`
		CUSTOMPROPERTY4   *string `json:"CUSTOMPROPERTY4,omitempty"`
		CUSTOMPROPERTY40  *string `json:"CUSTOMPROPERTY40,omitempty"`
		CUSTOMPROPERTY41  *string `json:"CUSTOMPROPERTY41,omitempty"`
		CUSTOMPROPERTY42  *string `json:"CUSTOMPROPERTY42,omitempty"`
		CUSTOMPROPERTY43  *string `json:"CUSTOMPROPERTY43,omitempty"`
		CUSTOMPROPERTY44  *string `json:"CUSTOMPROPERTY44,omitempty"`
		CUSTOMPROPERTY45  *string `json:"CUSTOMPROPERTY45,omitempty"`
		CUSTOMPROPERTY46  *string `json:"CUSTOMPROPERTY46,omitempty"`
		CUSTOMPROPERTY47  *string `json:"CUSTOMPROPERTY47,omitempty"`
		CUSTOMPROPERTY48  *string `json:"CUSTOMPROPERTY48,omitempty"`
		CUSTOMPROPERTY49  *string `json:"CUSTOMPROPERTY49,omitempty"`
		CUSTOMPROPERTY5   *string `json:"CUSTOMPROPERTY5,omitempty"`
		CUSTOMPROPERTY50  *string `json:"CUSTOMPROPERTY50,omitempty"`
		CUSTOMPROPERTY51  *string `json:"CUSTOMPROPERTY51,omitempty"`
		CUSTOMPROPERTY52  *string `json:"CUSTOMPROPERTY52,omitempty"`
		CUSTOMPROPERTY53  *string `json:"CUSTOMPROPERTY53,omitempty"`
		CUSTOMPROPERTY54  *string `json:"CUSTOMPROPERTY54,omitempty"`
		CUSTOMPROPERTY55  *string `json:"CUSTOMPROPERTY55,omitempty"`
		CUSTOMPROPERTY56  *string `json:"CUSTOMPROPERTY56,omitempty"`
		CUSTOMPROPERTY57  *string `json:"CUSTOMPROPERTY57,omitempty"`
		CUSTOMPROPERTY58  *string `json:"CUSTOMPROPERTY58,omitempty"`
		CUSTOMPROPERTY59  *string `json:"CUSTOMPROPERTY59,omitempty"`
		CUSTOMPROPERTY6   *string `json:"CUSTOMPROPERTY6,omitempty"`
		CUSTOMPROPERTY60  *string `json:"CUSTOMPROPERTY60,omitempty"`
		CUSTOMPROPERTY61  *string `json:"CUSTOMPROPERTY61,omitempty"`
		CUSTOMPROPERTY62  *string `json:"CUSTOMPROPERTY62,omitempty"`
		CUSTOMPROPERTY63  *string `json:"CUSTOMPROPERTY63,omitempty"`
		CUSTOMPROPERTY64  *string `json:"CUSTOMPROPERTY64,omitempty"`
		CUSTOMPROPERTY65  *string `json:"CUSTOMPROPERTY65,omitempty"`
		CUSTOMPROPERTY7   *string `json:"CUSTOMPROPERTY7,omitempty"`
		CUSTOMPROPERTY8   *string `json:"CUSTOMPROPERTY8,omitempty"`
		CUSTOMPROPERTY9   *string `json:"CUSTOMPROPERTY9,omitempty"`
		DEPARTMENTNAME    *string `json:"DEPARTMENTNAME,omitempty"`
		DEPARTMENTNUMBER  *string `json:"DEPARTMENTNUMBER,omitempty"`
		DISPLAYNAME       *string `json:"DISPLAYNAME,omitempty"`
		EMAIL             *string `json:"EMAIL,omitempty"`
		EMPLOYEECLASS     *string `json:"EMPLOYEECLASS,omitempty"`
		EMPLOYEEID        *string `json:"EMPLOYEEID,omitempty"`
		EMPLOYEETYPE      *string `json:"EMPLOYEETYPE,omitempty"`
		ENDDATE           *string `json:"ENDDATE,omitempty"`
		FIRSTNAME         *string `json:"FIRSTNAME,omitempty"`
		JOBCODE           *string `json:"JOBCODE,omitempty"`
		JOBCODEDESC       *string `json:"JOBCODEDESC,omitempty"`
		JOBDESCRIPTION    *string `json:"JOBDESCRIPTION,omitempty"`
		JOBFUNCTION       *string `json:"JOB_FUNCTION,omitempty"`
		LASTNAME          *string `json:"LASTNAME,omitempty"`
		LEAVESTATUS       *string `json:"LEAVESTATUS,omitempty"`
		LOCALE            *string `json:"LOCALE,omitempty"`
		LOCATION          *string `json:"LOCATION,omitempty"`
		LOCATIONDESC      *string `json:"LOCATIONDESC,omitempty"`
		LOCATIONNUMBER    *string `json:"LOCATIONNUMBER,omitempty"`
		MANAGER           *string `json:"MANAGER,omitempty"`
		MIDDLENAME        *string `json:"MIDDLENAME,omitempty"`
		ORGUNITID         *string `json:"ORGUNITID,omitempty"`
		PHONENUMBER       *string `json:"PHONENUMBER,omitempty"`
		PREFEREDFIRSTNAME *string `json:"PREFEREDFIRSTNAME,omitempty"`
		REGION            *string `json:"REGION,omitempty"`
		REGIONCODE        *string `json:"REGIONCODE,omitempty"`
		SECONDARYEMAIL    *string `json:"SECONDARYEMAIL,omitempty"`
		SECONDARYMANAGER  *string `json:"SECONDARYMANAGER,omitempty"`
		SECONDARYPHONE    *string `json:"SECONDARYPHONE,omitempty"`
		SITEID            *string `json:"SITEID,omitempty"`
		STARTDATE         *string `json:"STARTDATE,omitempty"`
		STATE             *string `json:"STATE,omitempty"`
		STATUSKEY         *string `json:"STATUSKEY,omitempty"`
		STREET            *string `json:"STREET,omitempty"`
		TERMDATE          *string `json:"TERMDATE,omitempty"`
		TITLE             *string `json:"TITLE,omitempty"`
		UPDATEDATE        *string `json:"UPDATEDATE,omitempty"`
		USERNAME          *string `json:"USERNAME,omitempty"`
	} `json:"users,omitempty"`
}

// PostAccountsJSONBody defines parameters for PostAccounts.
type PostAccountsJSONBody struct {
	Fields *string `json:"fields,omitempty"`
	Order  *string `json:"order,omitempty"`
	Q      *string `json:"q,omitempty"`
	Sort   *string `json:"sort,omitempty"`
}

// PostAccountsParams defines parameters for PostAccounts.
type PostAccountsParams struct {
	Offset   *int `form:"offset,omitempty" json:"offset,omitempty"`
	Pagesize *int `form:"pagesize,omitempty" json:"pagesize,omitempty"`
}

// PutChangePasswordJSONBody defines parameters for PutChangePassword.
type PutChangePasswordJSONBody struct {
	AccountID *string `json:"accountID,omitempty"`
	Password  *string `json:"password,omitempty"`
}

// PutEntitlementgroupsJSONBody defines parameters for PutEntitlementgroups.
type PutEntitlementgroupsJSONBody struct {
	AccountID     *string `json:"accountID,omitempty"`
	EntitlementID *string `json:"entitlementID,omitempty"`
}

// PutEntitlementGroupRemoveAccessJSONBody defines parameters for PutEntitlementGroupRemoveAccess.
type PutEntitlementGroupRemoveAccessJSONBody struct {
	AccountID     *string `json:"accountID,omitempty"`
	EntitlementID *string `json:"entitlementID,omitempty"`
}

// PutEntitlementRoleAddAccessJSONBody defines parameters for PutEntitlementRoleAddAccess.
type PutEntitlementRoleAddAccessJSONBody struct {
	AccountID     *string `json:"accountID,omitempty"`
	EntitlementID *string `json:"entitlementID,omitempty"`
}

// PutEntitlementRoleRemoveAccessJSONBody defines parameters for PutEntitlementRoleRemoveAccess.
type PutEntitlementRoleRemoveAccessJSONBody struct {
	AccountID     *string `json:"accountID,omitempty"`
	EntitlementID *string `json:"entitlementID,omitempty"`
}

// PostEntitlementsGroupsJSONBody defines parameters for PostEntitlementsGroups.
type PostEntitlementsGroupsJSONBody struct {
	Fields *string `json:"fields,omitempty"`
	Order  *string `json:"order,omitempty"`
	Sort   *string `json:"sort,omitempty"`
}

// PostEntitlementsGroupsParams defines parameters for PostEntitlementsGroups.
type PostEntitlementsGroupsParams struct {
	Offset   *int `form:"offset,omitempty" json:"offset,omitempty"`
	Pagesize *int `form:"pagesize,omitempty" json:"pagesize,omitempty"`
}

// PostEntitlementsRolesJSONBody defines parameters for PostEntitlementsRoles.
type PostEntitlementsRolesJSONBody struct {
	Fields *string `json:"fields,omitempty"`
	Order  *string `json:"order,omitempty"`
	Sort   *string `json:"sort,omitempty"`
}

// PostEntitlementsRolesParams defines parameters for PostEntitlementsRoles.
type PostEntitlementsRolesParams struct {
	Offset   *int `form:"offset,omitempty" json:"offset,omitempty"`
	Pagesize *int `form:"pagesize,omitempty" json:"pagesize,omitempty"`
}

// PatchUpdateAccountJSONBody defines parameters for PatchUpdateAccount.
type PatchUpdateAccountJSONBody = map[string]interface{}

// PostUsersJSONBody defines parameters for PostUsers.
type PostUsersJSONBody struct {
	Fields *string `json:"fields,omitempty"`
	Order  *string `json:"order,omitempty"`
	Sort   *string `json:"sort,omitempty"`
}

// PostUsersParams defines parameters for PostUsers.
type PostUsersParams struct {
	Offset   *int `form:"offset,omitempty" json:"offset,omitempty"`
	Pagesize *int `form:"pagesize,omitempty" json:"pagesize,omitempty"`
}

// PostAccountsJSONRequestBody defines body for PostAccounts for application/json ContentType.
type PostAccountsJSONRequestBody PostAccountsJSONBody

// PutChangePasswordJSONRequestBody defines body for PutChangePassword for application/json ContentType.
type PutChangePasswordJSONRequestBody PutChangePasswordJSONBody

// PostCreateAccountJSONRequestBody defines body for PostCreateAccount for application/json ContentType.
type PostCreateAccountJSONRequestBody = Createaccount

// PutEntitlementgroupsJSONRequestBody defines body for PutEntitlementgroups for application/json ContentType.
type PutEntitlementgroupsJSONRequestBody PutEntitlementgroupsJSONBody

// PutEntitlementGroupRemoveAccessJSONRequestBody defines body for PutEntitlementGroupRemoveAccess for application/json ContentType.
type PutEntitlementGroupRemoveAccessJSONRequestBody PutEntitlementGroupRemoveAccessJSONBody

// PutEntitlementRoleAddAccessJSONRequestBody defines body for PutEntitlementRoleAddAccess for application/json ContentType.
type PutEntitlementRoleAddAccessJSONRequestBody PutEntitlementRoleAddAccessJSONBody

// PutEntitlementRoleRemoveAccessJSONRequestBody defines body for PutEntitlementRoleRemoveAccess for application/json ContentType.
type PutEntitlementRoleRemoveAccessJSONRequestBody PutEntitlementRoleRemoveAccessJSONBody

// PostEntitlementsGroupsJSONRequestBody defines body for PostEntitlementsGroups for application/json ContentType.
type PostEntitlementsGroupsJSONRequestBody PostEntitlementsGroupsJSONBody

// PostEntitlementsRolesJSONRequestBody defines body for PostEntitlementsRoles for application/json ContentType.
type PostEntitlementsRolesJSONRequestBody PostEntitlementsRolesJSONBody

// PatchUpdateAccountJSONRequestBody defines body for PatchUpdateAccount for application/json ContentType.
type PatchUpdateAccountJSONRequestBody = PatchUpdateAccountJSONBody

// PatchUpdateUserJSONRequestBody defines body for PatchUpdateUser for application/json ContentType.
type PatchUpdateUserJSONRequestBody = Updateuser

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody PostUsersJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// This API returns the list of accounts
	// (POST /accounts)
	PostAccounts(w http.ResponseWriter, r *http.Request, params PostAccountsParams)
	// This API returns the list of account entitlement association for entitlement type group
	// (GET /accounts/group_memberships)
	GetAccountsGroupMemberships(w http.ResponseWriter, r *http.Request)
	// This API returns the list of account entitlement association for entitlement type role
	// (GET /accounts/role_memberships)
	GetAccountsRoleMemberships(w http.ResponseWriter, r *http.Request)
	// This API can be used to change password of an account
	// (PUT /changePassword)
	PutChangePassword(w http.ResponseWriter, r *http.Request)
	// This API creates an account
	// (POST /createAccount)
	PostCreateAccount(w http.ResponseWriter, r *http.Request)
	// This API grants group access to an account
	// (PUT /entitlement/group/addAccess)
	PutEntitlementgroups(w http.ResponseWriter, r *http.Request)
	// This API removes group access from an account
	// (PUT /entitlement/group/removeAccess)
	PutEntitlementGroupRemoveAccess(w http.ResponseWriter, r *http.Request)
	// This API grants role access to an account
	// (PUT /entitlement/role/addAccess)
	PutEntitlementRoleAddAccess(w http.ResponseWriter, r *http.Request)
	// This API removes role access from an account
	// (PUT /entitlement/role/removeAccess)
	PutEntitlementRoleRemoveAccess(w http.ResponseWriter, r *http.Request)
	// This API returns the list of group type entitlements
	// (POST /entitlements/groups)
	PostEntitlementsGroups(w http.ResponseWriter, r *http.Request, params PostEntitlementsGroupsParams)
	// This API returns the list of role type entitlements
	// (POST /entitlements/roles)
	PostEntitlementsRoles(w http.ResponseWriter, r *http.Request, params PostEntitlementsRolesParams)
	// This API deletes an account
	// (DELETE /removeAccount/{accountID})
	DeleteRemoveAccount(w http.ResponseWriter, r *http.Request, accountID string)
	// This API updates an account
	// (PATCH /updateAccount/{accountID})
	PatchUpdateAccount(w http.ResponseWriter, r *http.Request, accountID string)
	// This API updates a user
	// (PATCH /updateUser/{userName})
	PatchUpdateUser(w http.ResponseWriter, r *http.Request, userName string)
	// This API returns the list of users
	// (POST /users)
	PostUsers(w http.ResponseWriter, r *http.Request, params PostUsersParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// This API returns the list of accounts
// (POST /accounts)
func (_ Unimplemented) PostAccounts(w http.ResponseWriter, r *http.Request, params PostAccountsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// This API returns the list of account entitlement association for entitlement type group
// (GET /accounts/group_memberships)
func (_ Unimplemented) GetAccountsGroupMemberships(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// This API returns the list of account entitlement association for entitlement type role
// (GET /accounts/role_memberships)
func (_ Unimplemented) GetAccountsRoleMemberships(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// This API can be used to change password of an account
// (PUT /changePassword)
func (_ Unimplemented) PutChangePassword(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// This API creates an account
// (POST /createAccount)
func (_ Unimplemented) PostCreateAccount(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// This API grants group access to an account
// (PUT /entitlement/group/addAccess)
func (_ Unimplemented) PutEntitlementgroups(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// This API removes group access from an account
// (PUT /entitlement/group/removeAccess)
func (_ Unimplemented) PutEntitlementGroupRemoveAccess(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// This API grants role access to an account
// (PUT /entitlement/role/addAccess)
func (_ Unimplemented) PutEntitlementRoleAddAccess(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// This API removes role access from an account
// (PUT /entitlement/role/removeAccess)
func (_ Unimplemented) PutEntitlementRoleRemoveAccess(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// This API returns the list of group type entitlements
// (POST /entitlements/groups)
func (_ Unimplemented) PostEntitlementsGroups(w http.ResponseWriter, r *http.Request, params PostEntitlementsGroupsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// This API returns the list of role type entitlements
// (POST /entitlements/roles)
func (_ Unimplemented) PostEntitlementsRoles(w http.ResponseWriter, r *http.Request, params PostEntitlementsRolesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// This API deletes an account
// (DELETE /removeAccount/{accountID})
func (_ Unimplemented) DeleteRemoveAccount(w http.ResponseWriter, r *http.Request, accountID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// This API updates an account
// (PATCH /updateAccount/{accountID})
func (_ Unimplemented) PatchUpdateAccount(w http.ResponseWriter, r *http.Request, accountID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// This API updates a user
// (PATCH /updateUser/{userName})
func (_ Unimplemented) PatchUpdateUser(w http.ResponseWriter, r *http.Request, userName string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// This API returns the list of users
// (POST /users)
func (_ Unimplemented) PostUsers(w http.ResponseWriter, r *http.Request, params PostUsersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostAccounts operation middleware
func (siw *ServerInterfaceWrapper) PostAccounts(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostAccountsParams

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "pagesize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pagesize", r.URL.Query(), &params.Pagesize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pagesize", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAccounts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetAccountsGroupMemberships operation middleware
func (siw *ServerInterfaceWrapper) GetAccountsGroupMemberships(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccountsGroupMemberships(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetAccountsRoleMemberships operation middleware
func (siw *ServerInterfaceWrapper) GetAccountsRoleMemberships(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccountsRoleMemberships(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PutChangePassword operation middleware
func (siw *ServerInterfaceWrapper) PutChangePassword(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutChangePassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostCreateAccount operation middleware
func (siw *ServerInterfaceWrapper) PostCreateAccount(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostCreateAccount(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PutEntitlementgroups operation middleware
func (siw *ServerInterfaceWrapper) PutEntitlementgroups(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutEntitlementgroups(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PutEntitlementGroupRemoveAccess operation middleware
func (siw *ServerInterfaceWrapper) PutEntitlementGroupRemoveAccess(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutEntitlementGroupRemoveAccess(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PutEntitlementRoleAddAccess operation middleware
func (siw *ServerInterfaceWrapper) PutEntitlementRoleAddAccess(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutEntitlementRoleAddAccess(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PutEntitlementRoleRemoveAccess operation middleware
func (siw *ServerInterfaceWrapper) PutEntitlementRoleRemoveAccess(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutEntitlementRoleRemoveAccess(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostEntitlementsGroups operation middleware
func (siw *ServerInterfaceWrapper) PostEntitlementsGroups(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostEntitlementsGroupsParams

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "pagesize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pagesize", r.URL.Query(), &params.Pagesize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pagesize", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEntitlementsGroups(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostEntitlementsRoles operation middleware
func (siw *ServerInterfaceWrapper) PostEntitlementsRoles(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostEntitlementsRolesParams

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "pagesize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pagesize", r.URL.Query(), &params.Pagesize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pagesize", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEntitlementsRoles(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteRemoveAccount operation middleware
func (siw *ServerInterfaceWrapper) DeleteRemoveAccount(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "accountID" -------------
	var accountID string

	err = runtime.BindStyledParameterWithOptions("simple", "accountID", chi.URLParam(r, "accountID"), &accountID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountID", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteRemoveAccount(w, r, accountID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PatchUpdateAccount operation middleware
func (siw *ServerInterfaceWrapper) PatchUpdateAccount(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "accountID" -------------
	var accountID string

	err = runtime.BindStyledParameterWithOptions("simple", "accountID", chi.URLParam(r, "accountID"), &accountID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountID", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchUpdateAccount(w, r, accountID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PatchUpdateUser operation middleware
func (siw *ServerInterfaceWrapper) PatchUpdateUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "userName" -------------
	var userName string

	err = runtime.BindStyledParameterWithOptions("simple", "userName", chi.URLParam(r, "userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchUpdateUser(w, r, userName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostUsers operation middleware
func (siw *ServerInterfaceWrapper) PostUsers(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostUsersParams

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "pagesize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pagesize", r.URL.Query(), &params.Pagesize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pagesize", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/accounts", wrapper.PostAccounts)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/accounts/group_memberships", wrapper.GetAccountsGroupMemberships)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/accounts/role_memberships", wrapper.GetAccountsRoleMemberships)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/changePassword", wrapper.PutChangePassword)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/createAccount", wrapper.PostCreateAccount)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/entitlement/group/addAccess", wrapper.PutEntitlementgroups)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/entitlement/group/removeAccess", wrapper.PutEntitlementGroupRemoveAccess)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/entitlement/role/addAccess", wrapper.PutEntitlementRoleAddAccess)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/entitlement/role/removeAccess", wrapper.PutEntitlementRoleRemoveAccess)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/entitlements/groups", wrapper.PostEntitlementsGroups)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/entitlements/roles", wrapper.PostEntitlementsRoles)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/removeAccount/{accountID}", wrapper.DeleteRemoveAccount)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/updateAccount/{accountID}", wrapper.PatchUpdateAccount)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/updateUser/{userName}", wrapper.PatchUpdateUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users", wrapper.PostUsers)
	})

	return r
}
